[package]
name = "hello-docopt"
version = "0.1.0"
authors = ["lubingtan <lubingtan@126.com>"]
edition = "2018"

[dependencies]
docopt = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"